export const mockSchools = [
  {
      "id": 564,
      "name": "КГУ \"СОШ №14 города Павлодара\"",
      "date": "2023-10-09T04:55:39.343Z",
      "currentOrientation": 57,
      "priorityOrientation": 97,
      "currentSchoolPolicy": 66,
      "prioritySchoolPolicy": 32,
      "currentPhysicalEnvironment": 76,
      "priorityPhysicalEnvironment": 44,
      "currentSocialEnvironment": 32,
      "prioritySocialEnvironment": 46,
      "currentHealthSkills": 27,
      "priorityHealthSkills": 79,
      "currentCommunityLinks": 14,
      "priorityCommunityLinks": 32,
      "currentSchoolStuff": 92,
      "prioritySchoolsStuff": 18
  },
  {
      "id": 563,
      "name": " КГУ \"СОШ №19 г. Павлодара\" ",
      "date": "2023-10-15T01:56:32.774Z",
      "currentOrientation": 56,
      "priorityOrientation": 85,
      "currentSchoolPolicy": 68,
      "prioritySchoolPolicy": 95,
      "currentPhysicalEnvironment": 27,
      "priorityPhysicalEnvironment": 98,
      "currentSocialEnvironment": 81,
      "prioritySocialEnvironment": 37,
      "currentHealthSkills": 31,
      "priorityHealthSkills": 91,
      "currentCommunityLinks": 64,
      "priorityCommunityLinks": 36,
      "currentSchoolStuff": 82,
      "prioritySchoolsStuff": 56
  },
  {
      "id": 562,
      "name": "КГУ \"СОШ №25 г. Павлодара\"",
      "date": "2023-06-14T13:53:07.808Z",
      "currentOrientation": 60,
      "priorityOrientation": 57,
      "currentSchoolPolicy": 75,
      "prioritySchoolPolicy": 85,
      "currentPhysicalEnvironment": 95,
      "priorityPhysicalEnvironment": 53,
      "currentSocialEnvironment": 58,
      "prioritySocialEnvironment": 82,
      "currentHealthSkills": 20,
      "priorityHealthSkills": 74,
      "currentCommunityLinks": 17,
      "priorityCommunityLinks": 55,
      "currentSchoolStuff": 76,
      "prioritySchoolsStuff": 36
  },
  {
      "id": 561,
      "name": "КГУ \"СОПШДО №17 г.Павлодара\"",
      "date": "2023-11-21T01:09:57.414Z",
      "currentOrientation": 73,
      "priorityOrientation": 91,
      "currentSchoolPolicy": 73,
      "prioritySchoolPolicy": 94,
      "currentPhysicalEnvironment": 20,
      "priorityPhysicalEnvironment": 41,
      "currentSocialEnvironment": 96,
      "prioritySocialEnvironment": 47,
      "currentHealthSkills": 55,
      "priorityHealthSkills": 54,
      "currentCommunityLinks": 45,
      "priorityCommunityLinks": 80,
      "currentSchoolStuff": 39,
      "prioritySchoolsStuff": 71
  },
  {
      "id": 560,
      "name": " КГУ \"СОШ им. Б.Момышулы г. Палодара\" ",
      "date": "2023-05-15T09:53:20.188Z",
      "currentOrientation": 57,
      "priorityOrientation": 75,
      "currentSchoolPolicy": 38,
      "prioritySchoolPolicy": 90,
      "currentPhysicalEnvironment": 74,
      "priorityPhysicalEnvironment": 83,
      "currentSocialEnvironment": 19,
      "prioritySocialEnvironment": 88,
      "currentHealthSkills": 62,
      "priorityHealthSkills": 16,
      "currentCommunityLinks": 51,
      "priorityCommunityLinks": 13,
      "currentSchoolStuff": 60,
      "prioritySchoolsStuff": 76
  },
  {
      "id": 559,
      "name": "КГУ \"СОШ №35 г. Павлодара\" ",
      "date": "2023-03-04T12:38:39.202Z",
      "currentOrientation": 93,
      "priorityOrientation": 50,
      "currentSchoolPolicy": 52,
      "prioritySchoolPolicy": 87,
      "currentPhysicalEnvironment": 94,
      "priorityPhysicalEnvironment": 23,
      "currentSocialEnvironment": 46,
      "prioritySocialEnvironment": 20,
      "currentHealthSkills": 98,
      "priorityHealthSkills": 55,
      "currentCommunityLinks": 10,
      "priorityCommunityLinks": 81,
      "currentSchoolStuff": 49,
      "prioritySchoolsStuff": 96
  },
  {
      "id": 558,
      "name": " КГУ \"СОШ №37 г. Павлодара\"",
      "date": "2022-12-29T15:41:41.332Z",
      "currentOrientation": 69,
      "priorityOrientation": 37,
      "currentSchoolPolicy": 38,
      "prioritySchoolPolicy": 20,
      "currentPhysicalEnvironment": 77,
      "priorityPhysicalEnvironment": 42,
      "currentSocialEnvironment": 88,
      "prioritySocialEnvironment": 36,
      "currentHealthSkills": 47,
      "priorityHealthSkills": 94,
      "currentCommunityLinks": 51,
      "priorityCommunityLinks": 21,
      "currentSchoolStuff": 50,
      "prioritySchoolsStuff": 13
  },
  {
      "id": 557,
      "name": " КГУ «СОШ  № 40 города Павлодара»",
      "date": "2023-10-07T12:34:04.564Z",
      "currentOrientation": 92,
      "priorityOrientation": 27,
      "currentSchoolPolicy": 57,
      "prioritySchoolPolicy": 72,
      "currentPhysicalEnvironment": 82,
      "priorityPhysicalEnvironment": 13,
      "currentSocialEnvironment": 62,
      "prioritySocialEnvironment": 92,
      "currentHealthSkills": 13,
      "priorityHealthSkills": 50,
      "currentCommunityLinks": 82,
      "priorityCommunityLinks": 91,
      "currentSchoolStuff": 14,
      "prioritySchoolsStuff": 26
  },
  {
      "id": 556,
      "name": "КГУ \"Школа - лицей № 16 города Павлодара\"",
      "date": "2023-05-20T11:49:30.378Z",
      "currentOrientation": 18,
      "priorityOrientation": 24,
      "currentSchoolPolicy": 83,
      "prioritySchoolPolicy": 16,
      "currentPhysicalEnvironment": 11,
      "priorityPhysicalEnvironment": 80,
      "currentSocialEnvironment": 55,
      "prioritySocialEnvironment": 12,
      "currentHealthSkills": 17,
      "priorityHealthSkills": 30,
      "currentCommunityLinks": 84,
      "priorityCommunityLinks": 88,
      "currentSchoolStuff": 35,
      "prioritySchoolsStuff": 43
  },
  {
      "id": 555,
      "name": " КГУ \" СОШ №24 г. Павлодара\"",
      "date": "2023-06-16T19:36:15.898Z",
      "currentOrientation": 40,
      "priorityOrientation": 85,
      "currentSchoolPolicy": 85,
      "prioritySchoolPolicy": 91,
      "currentPhysicalEnvironment": 29,
      "priorityPhysicalEnvironment": 13,
      "currentSocialEnvironment": 15,
      "prioritySocialEnvironment": 74,
      "currentHealthSkills": 58,
      "priorityHealthSkills": 91,
      "currentCommunityLinks": 23,
      "priorityCommunityLinks": 17,
      "currentSchoolStuff": 83,
      "prioritySchoolsStuff": 24
  },
  {
      "id": 554,
      "name": "КГУ \"СОШ №39 г. Павлодара\" ",
      "date": "2023-06-09T17:42:20.840Z",
      "currentOrientation": 59,
      "priorityOrientation": 24,
      "currentSchoolPolicy": 26,
      "prioritySchoolPolicy": 54,
      "currentPhysicalEnvironment": 54,
      "priorityPhysicalEnvironment": 65,
      "currentSocialEnvironment": 38,
      "prioritySocialEnvironment": 58,
      "currentHealthSkills": 22,
      "priorityHealthSkills": 54,
      "currentCommunityLinks": 22,
      "priorityCommunityLinks": 48,
      "currentSchoolStuff": 22,
      "prioritySchoolsStuff": 45
  },
  {
      "id": 553,
      "name": " КГУ «СОШ  № 43 г.Павлодара»",
      "date": "2023-09-03T09:05:07.958Z",
      "currentOrientation": 15,
      "priorityOrientation": 49,
      "currentSchoolPolicy": 17,
      "prioritySchoolPolicy": 22,
      "currentPhysicalEnvironment": 94,
      "priorityPhysicalEnvironment": 50,
      "currentSocialEnvironment": 48,
      "prioritySocialEnvironment": 15,
      "currentHealthSkills": 86,
      "priorityHealthSkills": 21,
      "currentCommunityLinks": 56,
      "priorityCommunityLinks": 30,
      "currentSchoolStuff": 72,
      "prioritySchoolsStuff": 44
  },
  {
      "id": 552,
      "name": " КГУ \"СОШ № 41 г. Павлодара\"",
      "date": "2023-09-17T10:51:15.332Z",
      "currentOrientation": 70,
      "priorityOrientation": 46,
      "currentSchoolPolicy": 31,
      "prioritySchoolPolicy": 88,
      "currentPhysicalEnvironment": 56,
      "priorityPhysicalEnvironment": 48,
      "currentSocialEnvironment": 98,
      "prioritySocialEnvironment": 50,
      "currentHealthSkills": 55,
      "priorityHealthSkills": 86,
      "currentCommunityLinks": 76,
      "priorityCommunityLinks": 82,
      "currentSchoolStuff": 55,
      "prioritySchoolsStuff": 92
  },
  {
      "id": 551,
      "name": "КГУ \"СОШ № 7 г. Павлодара\"",
      "date": "2023-02-11T07:21:23.188Z",
      "currentOrientation": 19,
      "priorityOrientation": 96,
      "currentSchoolPolicy": 41,
      "prioritySchoolPolicy": 11,
      "currentPhysicalEnvironment": 32,
      "priorityPhysicalEnvironment": 76,
      "currentSocialEnvironment": 86,
      "prioritySocialEnvironment": 75,
      "currentHealthSkills": 78,
      "priorityHealthSkills": 30,
      "currentCommunityLinks": 65,
      "priorityCommunityLinks": 28,
      "currentSchoolStuff": 63,
      "prioritySchoolsStuff": 61
  },
  {
      "id": 550,
      "name": " КГУ \"СОШ№26 г. Павлодара\"",
      "date": "2023-09-08T00:28:19.825Z",
      "currentOrientation": 38,
      "priorityOrientation": 12,
      "currentSchoolPolicy": 83,
      "prioritySchoolPolicy": 100,
      "currentPhysicalEnvironment": 14,
      "priorityPhysicalEnvironment": 48,
      "currentSocialEnvironment": 61,
      "prioritySocialEnvironment": 77,
      "currentHealthSkills": 50,
      "priorityHealthSkills": 55,
      "currentCommunityLinks": 97,
      "priorityCommunityLinks": 44,
      "currentSchoolStuff": 37,
      "prioritySchoolsStuff": 40
  },
  {
      "id": 549,
      "name": "КГУ \"СОШ  №1 г. Павлодара\"",
      "date": "2023-02-07T14:14:46.900Z",
      "currentOrientation": 66,
      "priorityOrientation": 45,
      "currentSchoolPolicy": 84,
      "prioritySchoolPolicy": 100,
      "currentPhysicalEnvironment": 24,
      "priorityPhysicalEnvironment": 78,
      "currentSocialEnvironment": 63,
      "prioritySocialEnvironment": 28,
      "currentHealthSkills": 49,
      "priorityHealthSkills": 34,
      "currentCommunityLinks": 27,
      "priorityCommunityLinks": 15,
      "currentSchoolStuff": 45,
      "prioritySchoolsStuff": 92
  },
  {
      "id": 548,
      "name": "КГУ \"СОШ №2 г. Павлодара\" ",
      "date": "2022-12-30T03:07:46.583Z",
      "currentOrientation": 38,
      "priorityOrientation": 44,
      "currentSchoolPolicy": 28,
      "prioritySchoolPolicy": 35,
      "currentPhysicalEnvironment": 61,
      "priorityPhysicalEnvironment": 66,
      "currentSocialEnvironment": 47,
      "prioritySocialEnvironment": 56,
      "currentHealthSkills": 88,
      "priorityHealthSkills": 39,
      "currentCommunityLinks": 17,
      "priorityCommunityLinks": 43,
      "currentSchoolStuff": 33,
      "prioritySchoolsStuff": 11
  },
  {
      "id": 547,
      "name": "КГУ \"СОШ № 42 г. Павлодара\"",
      "date": "2023-08-01T15:29:51.977Z",
      "currentOrientation": 22,
      "priorityOrientation": 61,
      "currentSchoolPolicy": 36,
      "prioritySchoolPolicy": 11,
      "currentPhysicalEnvironment": 14,
      "priorityPhysicalEnvironment": 49,
      "currentSocialEnvironment": 92,
      "prioritySocialEnvironment": 71,
      "currentHealthSkills": 44,
      "priorityHealthSkills": 59,
      "currentCommunityLinks": 80,
      "priorityCommunityLinks": 66,
      "currentSchoolStuff": 95,
      "prioritySchoolsStuff": 42
  },
  {
      "id": 546,
      "name": " КГУ \"СОШ №28 г. Павлодара\"",
      "date": "2023-03-31T19:13:19.950Z",
      "currentOrientation": 27,
      "priorityOrientation": 22,
      "currentSchoolPolicy": 68,
      "prioritySchoolPolicy": 16,
      "currentPhysicalEnvironment": 88,
      "priorityPhysicalEnvironment": 76,
      "currentSocialEnvironment": 52,
      "prioritySocialEnvironment": 46,
      "currentHealthSkills": 21,
      "priorityHealthSkills": 18,
      "currentCommunityLinks": 100,
      "priorityCommunityLinks": 45,
      "currentSchoolStuff": 62,
      "prioritySchoolsStuff": 85
  },
  {
      "id": 545,
      "name": " КГУ \"СОШ №15 г. Павлодара\"",
      "date": "2023-11-14T22:29:12.829Z",
      "currentOrientation": 22,
      "priorityOrientation": 68,
      "currentSchoolPolicy": 13,
      "prioritySchoolPolicy": 65,
      "currentPhysicalEnvironment": 17,
      "priorityPhysicalEnvironment": 74,
      "currentSocialEnvironment": 25,
      "prioritySocialEnvironment": 16,
      "currentHealthSkills": 43,
      "priorityHealthSkills": 43,
      "currentCommunityLinks": 80,
      "priorityCommunityLinks": 61,
      "currentSchoolStuff": 78,
      "prioritySchoolsStuff": 41
  },
  {
      "id": 544,
      "name": " КГУ \"СОШ №5 г. Павлодара\"",
      "date": "2023-10-18T09:41:53.151Z",
      "currentOrientation": 40,
      "priorityOrientation": 44,
      "currentSchoolPolicy": 38,
      "prioritySchoolPolicy": 25,
      "currentPhysicalEnvironment": 70,
      "priorityPhysicalEnvironment": 96,
      "currentSocialEnvironment": 72,
      "prioritySocialEnvironment": 63,
      "currentHealthSkills": 95,
      "priorityHealthSkills": 27,
      "currentCommunityLinks": 60,
      "priorityCommunityLinks": 56,
      "currentSchoolStuff": 35,
      "prioritySchoolsStuff": 100
  },
  {
      "id": 543,
      "name": "КГУ  \"СОШ №30 г. Павлодара\"",
      "date": "2023-05-09T14:40:42.655Z",
      "currentOrientation": 60,
      "priorityOrientation": 44,
      "currentSchoolPolicy": 54,
      "prioritySchoolPolicy": 76,
      "currentPhysicalEnvironment": 12,
      "priorityPhysicalEnvironment": 63,
      "currentSocialEnvironment": 94,
      "prioritySocialEnvironment": 51,
      "currentHealthSkills": 98,
      "priorityHealthSkills": 71,
      "currentCommunityLinks": 34,
      "priorityCommunityLinks": 18,
      "currentSchoolStuff": 63,
      "prioritySchoolsStuff": 39
  },
  {
      "id": 542,
      "name": "КГУ \"СОШ им.К.Бекхожина\"",
      "date": "2023-06-20T15:45:41.642Z",
      "currentOrientation": 35,
      "priorityOrientation": 98,
      "currentSchoolPolicy": 35,
      "prioritySchoolPolicy": 31,
      "currentPhysicalEnvironment": 75,
      "priorityPhysicalEnvironment": 40,
      "currentSocialEnvironment": 29,
      "prioritySocialEnvironment": 11,
      "currentHealthSkills": 38,
      "priorityHealthSkills": 15,
      "currentCommunityLinks": 96,
      "priorityCommunityLinks": 74,
      "currentSchoolStuff": 73,
      "prioritySchoolsStuff": 15
  },
  {
      "id": 541,
      "name": " КГУ \"СОПШЭН №36 г. Павлодара\"",
      "date": "2022-12-20T05:33:36.277Z",
      "currentOrientation": 33,
      "priorityOrientation": 20,
      "currentSchoolPolicy": 53,
      "prioritySchoolPolicy": 82,
      "currentPhysicalEnvironment": 18,
      "priorityPhysicalEnvironment": 39,
      "currentSocialEnvironment": 79,
      "prioritySocialEnvironment": 52,
      "currentHealthSkills": 87,
      "priorityHealthSkills": 59,
      "currentCommunityLinks": 95,
      "priorityCommunityLinks": 22,
      "currentSchoolStuff": 25,
      "prioritySchoolsStuff": 40
  },
  {
      "id": 540,
      "name": "КГУ \"СОШ № 29 г. Павлодара\"",
      "date": "2023-11-11T01:04:08.838Z",
      "currentOrientation": 46,
      "priorityOrientation": 11,
      "currentSchoolPolicy": 44,
      "prioritySchoolPolicy": 80,
      "currentPhysicalEnvironment": 56,
      "priorityPhysicalEnvironment": 44,
      "currentSocialEnvironment": 46,
      "prioritySocialEnvironment": 20,
      "currentHealthSkills": 81,
      "priorityHealthSkills": 80,
      "currentCommunityLinks": 21,
      "priorityCommunityLinks": 66,
      "currentSchoolStuff": 49,
      "prioritySchoolsStuff": 12
  },
  {
      "id": 539,
      "name": "КГУ \"СОШ № 27 г.Павлодар\" ",
      "date": "2023-07-11T01:59:16.913Z",
      "currentOrientation": 100,
      "priorityOrientation": 57,
      "currentSchoolPolicy": 26,
      "prioritySchoolPolicy": 66,
      "currentPhysicalEnvironment": 87,
      "priorityPhysicalEnvironment": 71,
      "currentSocialEnvironment": 80,
      "prioritySocialEnvironment": 13,
      "currentHealthSkills": 15,
      "priorityHealthSkills": 98,
      "currentCommunityLinks": 37,
      "priorityCommunityLinks": 100,
      "currentSchoolStuff": 90,
      "prioritySchoolsStuff": 100
  },
  {
      "id": 538,
      "name": "E43 КГУ \"СОШ № 21 города Павлодара\" ",
      "date": "2023-09-09T00:50:47.361Z",
      "currentOrientation": 82,
      "priorityOrientation": 96,
      "currentSchoolPolicy": 50,
      "prioritySchoolPolicy": 74,
      "currentPhysicalEnvironment": 22,
      "priorityPhysicalEnvironment": 91,
      "currentSocialEnvironment": 96,
      "prioritySocialEnvironment": 45,
      "currentHealthSkills": 45,
      "priorityHealthSkills": 83,
      "currentCommunityLinks": 57,
      "priorityCommunityLinks": 50,
      "currentSchoolStuff": 47,
      "prioritySchoolsStuff": 70
  },
  {
      "id": 537,
      "name": "КГУ \"СОШГ № 9 г. Павлодара\"",
      "date": "2023-01-13T08:06:31.122Z",
      "currentOrientation": 30,
      "priorityOrientation": 16,
      "currentSchoolPolicy": 95,
      "prioritySchoolPolicy": 43,
      "currentPhysicalEnvironment": 51,
      "priorityPhysicalEnvironment": 49,
      "currentSocialEnvironment": 89,
      "prioritySocialEnvironment": 86,
      "currentHealthSkills": 35,
      "priorityHealthSkills": 42,
      "currentCommunityLinks": 79,
      "priorityCommunityLinks": 35,
      "currentSchoolStuff": 56,
      "prioritySchoolsStuff": 61
  },
  {
      "id": 536,
      "name": " КГУ  «Средняя общеобразовательная школа №23»",
      "date": "2023-02-06T10:40:33.932Z",
      "currentOrientation": 84,
      "priorityOrientation": 14,
      "currentSchoolPolicy": 86,
      "prioritySchoolPolicy": 97,
      "currentPhysicalEnvironment": 25,
      "priorityPhysicalEnvironment": 96,
      "currentSocialEnvironment": 44,
      "prioritySocialEnvironment": 13,
      "currentHealthSkills": 80,
      "priorityHealthSkills": 86,
      "currentCommunityLinks": 41,
      "priorityCommunityLinks": 39,
      "currentSchoolStuff": 59,
      "prioritySchoolsStuff": 23
  },
  {
      "id": 535,
      "name": " КГУ  «Средняя общеобразовательная школа №17»",
      "date": "2023-05-11T06:59:22.779Z",
      "currentOrientation": 24,
      "priorityOrientation": 15,
      "currentSchoolPolicy": 99,
      "prioritySchoolPolicy": 99,
      "currentPhysicalEnvironment": 46,
      "priorityPhysicalEnvironment": 78,
      "currentSocialEnvironment": 43,
      "prioritySocialEnvironment": 10,
      "currentHealthSkills": 80,
      "priorityHealthSkills": 56,
      "currentCommunityLinks": 87,
      "priorityCommunityLinks": 10,
      "currentSchoolStuff": 45,
      "prioritySchoolsStuff": 96
  },
  {
      "id": 534,
      "name": "E39 КГУ  «Средняя общеобразовательная школа №12»",
      "date": "2023-04-26T12:31:24.715Z",
      "currentOrientation": 92,
      "priorityOrientation": 33,
      "currentSchoolPolicy": 44,
      "prioritySchoolPolicy": 16,
      "currentPhysicalEnvironment": 31,
      "priorityPhysicalEnvironment": 82,
      "currentSocialEnvironment": 13,
      "prioritySocialEnvironment": 26,
      "currentHealthSkills": 66,
      "priorityHealthSkills": 46,
      "currentCommunityLinks": 42,
      "priorityCommunityLinks": 91,
      "currentSchoolStuff": 79,
      "prioritySchoolsStuff": 78
  }
]